# Generated by Django 2.0.5 on 2018-05-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=64, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=64, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('case_name', models.CharField(max_length=64)),
                ('case_id', models.IntegerField()),
                ('step_order', models.IntegerField()),
                ('locator', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=64)),
                ('ops', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=1024)),
                ('ret_assert', models.CharField(max_length=256)),
                ('required', models.IntegerField()),
                ('ops_detail', models.CharField(max_length=64)),
                ('pic_address', models.CharField(max_length=256)),
                ('imgdiff', models.IntegerField()),
            ],
        ),
    ]
