# Generated by Django 2.0.5 on 2018-05-27 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_testcase_testcasestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasestep',
            name='element_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
