# Generated by Django 2.0.5 on 2018-06-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testcasestep_reg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='url',
            field=models.CharField(default='work.1688.com', max_length=64),
        ),
        migrations.AlterField(
            model_name='testcasestep',
            name='case_id',
            field=models.IntegerField(auto_created=1),
        ),
    ]
