INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, ops, value, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create_entrance', 1,'xpath', '//span/button[@type="button" and contains(@class,"next-btn-primary")]', 'button', 'click','null', 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, ops, value, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 1,'id', 'name', 'input', 'sendkey','auto1501', 'null', 1, '新建员工-输入姓名');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 1, 'xpath', '//span/button[@type="button" and contains(@class,"next-btn-primary")]', 'button', 'basic', 'click', '',"no_reg", 'null', 1, '新建员工-入口');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 2, 'id', 'name', 'input', 'basic', 'sendkey', 'auto1501',"[A-Z]\\d[A-Z]\\d[A-Z]\\d", 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 3, 'xpath', '//span/input[@type="radio" and @value="2"]', 'button', 'basic', 'click','','no_reg', 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 4, 'xpath', '//span/input[@type="text" and @placeholder="请输入账号名"]', 'input', 'basic', 'sendkey', 'haha','no_reg', 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 5, 'xpath', '//span/input[@type="password" and @placeholder="由数字与字母组成6～16的字符"]', 'input', 'basic', 'sendkey', '123456','no_reg', 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 6, 'xpath', '//span/input[@type="password" and @placeholder="请重复再输一遍"]', 'input', 'basic', 'sendkey', '123456','no_reg', 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 7, 'xpath', '//span/span[@class="next-select-inner"]', 'button', 'basic', 'click','','no_reg', 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 8, 'xpath', '//li/a[@class="next-tree-node-handle"]', 'button', 'basic', 'click','','no_reg', 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 9, 'id', 'securityPhone', 'input', 'basic', 'sendkey', '14755667788',"\\d{11}", 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 10, 'xpath', '//div[@label="职务" and contains(@class,next-form-item)]/div/span/span[@class="next-select-inner"]', 'button', 'basic', 'click','','no_reg', 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 11, 'xpath', '//ul[@class="next-menu-content"]/li', 'button', 'list', 'click','','no_reg', 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 12, 'xpath', '//div[@label="岗位" and contains(@class,next-form-item)]/div/span/span[@class="next-select-inner"]', 'button', 'basic', 'click','','no_reg', 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 13, 'xpath', '//ul[@class="next-menu-content"]/li', 'button', 'list', 'click','','no_reg', 'null', 1, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 14, 'id', 'employeeNumber', 'input', 'basic', 'sendkey', 'haha11',"\\d{11}", 'null', 0, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 15, 'id', 'nickName', 'input', 'basic', 'sendkey', 'haha22',"[A-Z]\\d[A-Z]\\d[A-Z]\\d", 'null', 0, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 16, 'id', 'personalMobilePhone', 'input', 'basic', 'sendkey', '13455667788',"\\d{11}", 'null', 0, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 17, 'id', 'email', 'input', 'basic', 'sendkey', 'haha@gg.com',"^([a-zA-Z0-9_-]{5,10})@([a-zA-Z0-9_-]{5})(\\.com)", 'null', 0, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 18, 'id', 'fixedPhone', 'input', 'basic', 'sendkey', '0571-88776655',"\\d{11}", 'null', 0, '新建员工');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 19, 'id', 'workLocation', 'input', 'basic', 'sendkey', '杭州','no_reg', 'null', 0, '新建员工');

#create material
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_material_create', 1, 'css_selector', "input[valid-name='title']", 'input', 'basic', 'sendkey', 'testAuto','no_reg', 'null', 1, '新建物料');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_material_create', 2, 'xpath', "//span/input[@name='brandName']", 'input', 'basic', 'sendkey', 'testAuto',"[A-Z]\\d[A-Z]\\d[A-Z]\\d", 'null', 0, '新建物料');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_material_create', 3, 'xpath', "//span/input[@name='brandModel']", 'input', 'basic', 'sendkey', 'testAuto',"[A-Z]\\d[A-Z]\\d[A-Z]\\d", 'null', 0, '新建物料');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_material_create', 4, 'xpath', "//div/input[@name='productCode']", 'input', 'basic', 'sendkey', 'testAuto',"[A-Z]\\d[A-Z]\\d[A-Z]\\d", 'null', 0, '新建物料');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_material_create', 5, 'xpath', '//div[contains(@class,go-combobox)]/input[@class="result" and @type="text"]', 'button', 'basic', 'click','','no_reg', 'null', 1, '新建物料');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_material_create', 6, 'xpath', '//div[contains(@class,fd-clr)]/ul/li[@class="go-combobox-item"]', 'button', 'list', 'click','','no_reg', 'null', 1, '新建物料');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_material_create', 7, 'xpath', "//div/input[@name='referencePrice']", 'input', 'basic', 'sendkey', 'testAuto',"\\d\\d\\d", 'null', 0, '新建物料');
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_material_create', 8, 'xpath', "//div/input[@name='purchaseAnnual']", 'input', 'basic', 'sendkey', 'testAuto',"\\d\\d\\d", 'null', 0, '新建物料');


########new###########
INSERT INTO myapp_testcase(step_name, case_name, case_id, step_order,locator, location, type, element_type, ops, value, reg_type, ret_assert, required, ops_detail, pic_address, imgdiff) VALUES ('test_step','caigou_member_create', 1, 1, 'xpath', '//span/button[@type="button" and contains(@class,"next-btn-primary")]', 'button', 'basic', 'click', '',"no_reg", 'null', 1, '新建员工-入口','http://www.baidu.com',0);
INSERT INTO selUops(gmt_create, name, ops_order,locator, location, type, element_type, ops, value, reg_type, assert, required, ops_detail) VALUES (NOW(),'caigou_member_create', 2, 'id', 'name', 'input', 'basic', 'sendkey', 'auto1501',"[A-Z]\\d[A-Z]\\d[A-Z]\\d", 'null', 1, '新建员工');

INSERT INTO myapp_testcasestep(add_time, step_name, case_name, case_id, step_order,locator, location, type, element_type, ops, value, reg_type, ret_assert, required, ops_detail, pic_address, imgdiff) VALUES (NOW(), 'new','', 0, 0, 'xpath', '//span/button[@type="button" and contains(@class,"next-btn-primary")]', 'button', 'basic', 'click', '',"", 'null', 1, '','http://www.baidu.com',0);

